service: gerenciador-tarefas-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

plugins:
  - serverless-offline
functions:
  authRegister:
    handler: src/functions/auth/handler.register
    events:
      - httpApi:
          path: /auth/register
          method: post

  authLogin:
    handler: src/functions/auth/handler.login
    events:
      - httpApi:
          path: /auth/login
          method: post

  authProfile:
    handler: src/functions/auth/handler.profile
    events:
      - httpApi:
          path: /auth/profile
          method: get

  updateAuthProfile:
    handler: src/functions/auth/handler.updateProfile
    events:
      - httpApi:
          path: /auth/profile
          method: patch

  createProject:
    handler: src/functions/projects/handler.create
    events:
      - httpApi:
          path: /projects
          method: post

  listProjects:
    handler: src/functions/projects/handler.list
    events:
      - httpApi:
          path: /projects
          method: get

  updateProject:
    handler: src/functions/projects/handler.update
    events:
      - httpApi:
          path: /projects/{id}
          method: patch

  deleteProject:
    handler: src/functions/projects/handler.remove
    events:
      - httpApi:
          path: /projects/{id}
          method: delete

  addProjectMember:
    handler: src/functions/projects/handler.addMember
    events:
      - httpApi:
          path: /projects/{id}/members
          method: post

  createTask:
    handler: src/functions/tasks/handler.create
    events:
      - httpApi:
          path: /tasks
          method: post

  getTasks:
    handler: src/functions/tasks/handler.list
    events:
      - httpApi:
          path: /projects/{projectId}/tasks
          method: get

  getTaskById:
    handler: src/functions/tasks/handler.getById
    events:
      - httpApi:
          path: /tasks/{id}
          method: get

  updateTaskStatus:
    handler: src/functions/tasks/handler.updateStatus
    events:
      - httpApi:
          path: /tasks/{id}/status
          method: patch

  updateTask:
    handler: src/functions/tasks/handler.update
    events:
      - httpApi:
          path: /tasks/{id}
          method: patch

  deleteTask:
    handler: src/functions/tasks/handler.remove
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete

  createCategory:
    handler: src/functions/categories/handler.create
    events:
      - httpApi:
          path: /categories
          method: post

  listCategories:
    handler: src/functions/categories/handler.list
    events:
      - httpApi:
          path: /categories
          method: get

  deleteCategory:
    handler: src/functions/categories/handler.delete
    events:
      - httpApi:
          path: /categories/{id}
          method: delete

  swaggerDocs:
    handler: src/functions/docs/handler.swagger
    events:
      - httpApi:
          path: /docs
          method: get
  
  